### ISSUE TITLE
If target_zone is grouped the output_id is not retrieved

### ISSUE THREAD

**Issue by doctorfree** [pavoni/pyroon#36]
In the examples there is the following code:

    # get target zone output_id
zones = roonapi.zones
output_id = [
    output["zone_id"]
    for output in zones.values()
    if output["display_name"] == target_zone
][0]
print("OUTPUT ID", output_id)

The specified target_zone must match the returned output display_name exactly. I replaced that == match with the Python 'in' keyword to do substring matching as follows:

    # get target zone output_id
zones = roonapi.zones
output_id = [
    output["zone_id"]
    for output in zones.values()
    if target_zone in output["display_name"]
][0]
print("OUTPUT ID", output_id)

This matches target_zone if it is grouped or ungrouped.

I suppose it is a design decision. Do you want the API acting on a grouped zone if only one of the zones in the grouping is specified. In my case, I do so I made this change. Maybe it's not an issue so much as something that would be good to add to the examples. Anyway, thanks for the effort! I'm using this project successfully to control Roon via Siri + SSH Shortcuts + shell scripts and python scripts on a server that can reach my Roon Core. It all works pretty well for an early release.

**Comment by pavoni** [comment]
Sorry for the slow reply.

At least in my view the way the roon code removes the grouped zones - and renames the main zone is a little strange. I think in a real implementation a designer will need to decide whether they want to dynamically change zones following room - or try and keep than static. In HA I keep them static, since that matches the design of that application better.

As you rightly point out - my demo code is a bit shaky - would be happy to change - esp if you feel like putting your code in a PR!  

And delighted to see the code being used outside Home Assistant!

Thanks for taking the time to comment.
