### ISSUE TITLE
endpoint play_media, doesn't work with existing

### ISSUE THREAD

**Issue by smangels** [pavoni/pyroon#50]
* there is an existing playlist called "wellenrauschen"
* the endpoint is working for a "Play Artists" or a specific album
* I try to play it with `api.play_media(self.zone_id, ['Playlists', 'wellenrauschen], action="Play Now")`
* API returns `ERROR roonapi: Could not find media path element 'wellenrauschen' in []`

![Screenshot_20220206-184345_Roon](https://user-images.githubusercontent.com/4567226/152693853-45e659fc-1b0f-4b15-920d-a17e399b4c5b.jpg)

**Comment by pavoni** [comment]
The roon api media path isn't necessarily what you'd guess from using the app.

I tried to add really good error messages to deal with this.

Start with something like 

```
roonapi.play_media(
    output_id, [""]
)
```

You should get an error like 
```
2022-02-06 23:42:35,977 ERROR  roonapi -- Could not find media path element '' in ['Library', 'Playlists', 'My Live Radio', 'Genres', 'Qobuz', 'Settings']
```
This will give you the options at that point in the path, which you can hopefully use to build up the command you need.

**Comment by smangels** [comment]
I think I've used the API correctly and did exactly as you recommended. So my path was ['Playlists', <playlist-name>] But I was not able to grab the media information. The Python API replied with "no media found for". The error message can be found here: https://github.com/pavoni/pyroon/blob/e157ca11d63204682f74a81f9a6dc86d851ed2e1/roonapi/roonapi.py#L572

**Comment by pavoni** [comment]
The error in your first message `ERROR roonapi: Could not find media path element 'wellenrauschen' in []` means that the code was looking for `wellenrauschen` at a point where there was nothing at that point in the hierarchy. It also implied that it had found 'Playlists' ok.

The error you link in your second message is different - in that case it's found the media to play - but is looking for a specific command - and failing to find it.

Because this is all dynamic - I'm afraid you're going to need to investigate to try and find what's happening.

Perhaps try the command I suggested - and let me know the exact message.
