### ISSUE TITLE
Fetching cover art

### ISSUE THREAD

**Issue by jason-a69** [pavoni/pyroon#53]
Hello,

I am trying to write some python code to fetch the cover art for the track that is currently playing, the JS code is here

https://roonlabs.github.io/node-roon-api/other_node-roon-api-image_lib.js.html

I have had a look in 
https://github.com/pavoni/pyroon/blob/master/roonapi/roonapi.py

and I do not think that functionality has been implemented yet, am I wrong?

Many thanks

Jason

**Comment by pavoni** [comment]
You can see an example getting cover art here:-

https://github.com/home-assistant/core/blob/dev/homeassistant/components/roon/media_player.py#L238

Using the call here:-

https://github.com/pavoni/pyroon/blob/master/roonapi/roonapi.py#L169

It isn't exactly the same since it returns an http link, rather than the image itself (which I think is what the api call you link does).

If you want the image itself I'm very open to a PR.

**Comment by jason-a69** [comment]
Yeah, I was wrong! It is there already.

Thanks very much, I'll use the media_player.py as a template.

**Comment by jason-a69** [comment]
Hi Greg,

i have managed to get my code to work and I would like to publish it on here, do you mind if link back to your code? I would not have been able to achieve what I wanted to do without your libraries, so thanks very much for that. I am happy for you to see the code before I publish it.

Cheers,

Jason

**Comment by pavoni** [comment]
That’s great, glad it helped. I wasn’t the initial author btw.

Feel free to link, that’s the open source way.

I could add something to the read me with a couple of links to example code, including your repo. Might help future users

**Comment by jason-a69** [comment]
Ok, leave it with me, let me get the repo together and get back to you.
